using System.Runtime.Serialization;

namespace MobileApp.Host.Models;

public enum Country
{
    Afghanistan,
    Albania,
    Algeria,
    Andorra,
    Angola,
    [EnumMember(Value = "Antigua and Barbuda")]
    AntiguaAndBarbuda,
    Argentina,
    Armenia,
    Australia,
    Austria,
    Azerbaijan,
    Bahamas,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Benin,
    Bhutan,
    Bolivia,
    [EnumMember(Value = "Bosnia and Herzegovina")]
    BosniaAndHerzegovina,
    Botswana,
    Brazil,
    Brunei,
    Bulgaria,
    [EnumMember(Value = "Burkina Faso")]
    BurkinaFaso,
    Burundi,
    [EnumMember(Value = "Côte d'Ivoire")]
    CôteDIvoire,
    [EnumMember(Value = "Cabo Verde")]
    CaboVerde,
    Cambodia,
    Cameroon,
    Canada,
    [EnumMember(Value = "Central African Republic")]
    CentralAfricanRepublic,
    Chad,
    Chile,
    China,
    Colombia,
    Comoros,
    Congo,
    [EnumMember(Value = "Costa Rica")]
    CostaRica,
    Croatia,
    Cuba,
    Cyprus,
    Czechia,
    [EnumMember(Value = "Democratic Republic of the Congo")]
    DemocraticRepublicOfTheCongo,
    Denmark,
    Djibouti,
    Dominica,
    [EnumMember(Value = "Dominican Republic")]
    DominicanRepublic,
    Ecuador,
    Egypt,
    [EnumMember(Value = "El Salvador")]
    ElSalvador,
    [EnumMember(Value = "Equatorial Guinea")]
    EquatorialGuinea,
    Eritrea,
    Estonia,
    Eswatini,
    Ethiopia,
    Fiji,
    Finland,
    France,
    Gabon,
    Gambia,
    Georgia,
    Germany,
    Ghana,
    Greece,
    Grenada,
    Guatemala,
    Guinea,
    [EnumMember(Value = "Guinea Bissau")]
    GuineaBissau,
    Guyana,
    Haiti,
    [EnumMember(Value = "Holy See")]
    HolySee,
    Honduras,
    Hungary,
    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland,
    Israel,
    Italy,
    Jamaica,
    Japan,
    Jordan,
    Kazakhstan,
    Kenya,
    Kiribati,
    Kuwait,
    Kyrgyzstan,
    Laos,
    Latvia,
    Lebanon,
    Lesotho,
    Liberia,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Madagascar,
    Malawi,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    [EnumMember(Value = "Marshall Islands")]
    MarshallIslands,
    Mauritania,
    Mauritius,
    Mexico,
    Micronesia,
    Moldova,
    Monaco,
    Mongolia,
    Montenegro,
    Morocco,
    Mozambique,
    Myanmar,
    Namibia,
    Nauru,
    Nepal,
    Netherlands,
    [EnumMember(Value = "New Zealand")]
    NewZealand,
    Nicaragua,
    Niger,
    Nigeria,
    [EnumMember(Value = "North Korea")]
    NorthKorea,
    [EnumMember(Value = "North Macedonia")]
    NorthMacedonia,
    Norway,
    Oman,
    Pakistan,
    Palau,
    [EnumMember(Value = "Palestine State")]
    PalestineState,
    Panama,
    [EnumMember(Value = "Papua New Guinea")]
    PapuaNewGuinea,
    Paraguay,
    Peru,
    Philippines,
    Poland,
    Portugal,
    Qatar,
    Romania,
    Russia,
    Rwanda,
    [EnumMember(Value = "Saint Kitts and Nevis")]
    SaintKittsAndNevis,
    [EnumMember(Value = "Saint Lucia")]
    SaintLucia,
    [EnumMember(Value = "Saint Vincent and the Grenadines")]
    SaintVincentAndTheGrenadines,
    Samoa,
    [EnumMember(Value = "San Marino")]
    SanMarino,
    [EnumMember(Value = "Sao Tome and Principe")]
    SaoTomeAndPrincipe,
    [EnumMember(Value = "Saudi Arabia")]
    SaudiArabia,
    Senegal,
    Serbia,
    Seychelles,
    [EnumMember(Value = "Sierra Leone")]
    SierraLeone,
    Singapore,
    Slovakia,
    Slovenia,
    [EnumMember(Value = "Solomon Islands")]
    SolomonIslands,
    Somalia,
    [EnumMember(Value = "South Africa")]
    SouthAfrica,
    [EnumMember(Value = "South Korea")]
    SouthKorea,
    [EnumMember(Value = "South Sudan")]
    SouthSudan,
    Spain,
    [EnumMember(Value = "Sri Lanka")]
    SriLanka,
    Sudan,
    Suriname,
    Sweden,
    Switzerland,
    Syria,
    Tajikistan,
    Tanzania,
    Thailand,
    [EnumMember(Value = "Timor Leste")]
    TimorLeste,
    Togo,
    Tonga,
    [EnumMember(Value = "Trinidad and Tobago")]
    TrinidadAndTobago,
    Tunisia,
    Turkey,
    Turkmenistan,
    Tuvalu,
    Uganda,
    Ukraine,
    [EnumMember(Value = "United Arab Emirates")]
    UnitedArabEmirates,
    [EnumMember(Value = "United Kingdom")]
    UnitedKingdom,
    [EnumMember(Value = "United States of America")]
    UnitedStatesOfAmerica,
    Uruguay,
    Uzbekistan,
    Vanuatu,
    Venezuela,
    Vietnam,
    Yemen,
    Zambia,
    Zimbabwe,
}