services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jG1cv1L81%8Y
      - POSTGRES_DB=MobileApp
    ports:
      - '5432:5432'
    volumes: 
      - ./PostgreSQL/data:/var/lib/postgresql/data
    networks:
      - shared-network
  db-adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8090:8080 
    networks:
      - shared-network
  anyone-backend:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=AnyOneApi;Username=postgres;Password=jG1cv1L81%8Y
      - ASPNETCORE_URLS=http://+:5173
      - Authentication__SecretKey=d2s3kjhds1lkg4khlfh2sdfk4sf7df3jsd2klfhsd3kfh==
      - Authentication__Audience=AnyOneAppAudience
      - Authentication__Issuer=AnyOneAppIssuer
    ports:
      - 5173:5173
    volumes: 
      - ./AnyOneApi/Logs:/app/MobileApp.Host/bin/Release/net6.0/publish/Logs
    networks:
      - shared-network
networks:
  shared-network:
    driver: bridge