services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jG1cv1L81%8Y
      - POSTGRES_DB=MobileApp
    ports:
      - '5432:5432'
    volumes: 
      - ./PostgreSQL/data:/var/lib/postgresql/data
    networks:
      - shared-network
  db-adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - 8090:8080 
    networks:
      - shared-network
  mobileapp-backend:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=MobileApp;Username=postgres;Password=jG1cv1L81%8Y
      - ASPNETCORE_URLS=http://+:5173
      - Authentication__SecretKey=H+l.%;.G?'EUHXE]m*?r!6AiYdQ&x*.oI=f8=5z<Gr}G_M'tdgIz_e:I&Xe,{re
      - Authentication__Audience=mobileAppAudience
      - Authentication__Issuer=mobileAppIssuer
    ports:
      - 5173:5173
    volumes: 
      - ./MobileApp/Logs:/app/MobileApp.Host/bin/Release/net6.0/publish/Logs
    networks:
      - shared-network
networks:
  shared-network:
    external: true