name: Deploy to External Server
on:
  push:
    branches:
      - developer
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy files to external server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} rsync -avz --delete . ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PORT }}/

      - name: Run deployment script on server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -p $SSH_PORT ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /root/MobileApp/Docker
            docker-compose down
            docker system prune -af
            docker-compose build
            docker-compose up -d
          EOF
